# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Download Github NPM Package v1
# Install NPM packages from GitHub.
- task: DownloadGithubNpmPackage@1
  inputs:
    packageName: 'my-npm-package' # Required. Specify the name of the NPM package.
    version: '1.2.3' # Required. Specify the version of the package to install.
    externalRegistryCredentials: 'my-github-registry' # Required. Specify the name of the external registry credential to use.
    installDirectory: '$(Agent.TempDirectory)/my-npm-package' # Optional. Specify a specific folder to install the package. 


- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'SnykUsedforPipelinePurposes'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: true